name: Create Card for PR merge

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
