name: Create Card for PR merge

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install --force

      - name: Add Trello Card for PR
        uses: ./.github/workflows/addTrelloCardsForReleaseAction
        with:
          milestone-label: ${{ github.event.pull_request.milestone.number }}
          name-of-card: ${{ github.event.pull_request.title }}
          description-of-card: ${{ github.event.pull_request.body }}
          pr-link: ${{ github.event.pull_request._links.html.href }}
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-api-token: ${{ secrets.TRELLO_API_TOKEN }}