name: Create Card for PR merge

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development'
    runs-on: ubuntu-latest
    steps:
      - uses: addTrelloCardsForReleaseAction/action.yml
        with:
          name-of-card: ${{ github.event.pull_request.title }}
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-api-token: ${{ secrets.TRELLO_API_TOKEN }}
