name: Update Version on Release

on:
  release:
    types:
      - created

permissions: write-all

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: development

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn all-aboard

  create-pull-request:
    runs-on: ubuntu-latest
    name: "[chore] Merge pull request from staging to develop"
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: development

      - name: Run auto-merge-action
        id: run-auto-merge-action
        uses: yyoshiki41/auto-merge-action@v1
        with:
          github-token: ${{ secrets.MERGE_TOKEN }}
          base: development
          head: release
