name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.x' # Change to your desired .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Run Unit Tests
        run: |
             cd FrameworkUnitTests 
             dotnet test --configuration Release --filter TestCategory!=SkipOnCI
