name: CI

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: FrameworkUnitTests.dll
          searchFolder: .\FrameworkUnitTests\FrameworkUnitTests\bin\Debug\
          runInParallel: true