name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run tests
        uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: FrameworkUnitTests.dll
          searchFolder: .\FrameworkUnitTests\FrameworkUnitTests\bin\Debug\
          runInParallel: true

