name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with .NET Framework 4.7
        run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /p:Configuration=Release /p:Platform=\"Any CPU\" FrameworkUnitTests.sln"


      - name: Run tests
        run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\VSTest.console.exe FrameworkUnitTests.FrameworkUnitTests.dll

